package com.example.voicellm.ui

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    // Common
    val back: String,
    val cancel: String,
    val delete: String,
    val save: String,
    val activate: String,
    val download: String,
    val retry: String,
    val errorLabel: String,
    val activeLabel: String,
    val ok: String,
    // Wizard
    val wizardWelcome: String,
    val wizardSubtitle: String,
    val wizardEasySetupInfo: String,
    val wizardEasySetupLlm: String,
    val wizardEasySetupVoice: String,
    val wizardEasySetupTotal: String,
    val wizardStartEasySetup: String,
    val wizardSkip: String,
    val wizardModelLabel: String,
    val wizardVoiceLabel: String,
    val wizardStarting: String,
    val wizardExtracting: String,
    val wizardReady: String,
    val wizardLangTitle: String,
    val wizardLangSubtitle: String,
    val wizardMemoryTitle: String,
    val wizardMemorySubtitle: String,
    val wizardMemoryYes: String,
    val wizardMemoryYesDesc: String,
    val wizardMemoryNo: String,
    val wizardMemoryNoDesc: String,
    val wizardMemoryHint: String,
    // Start
    val startSubtitle: String,
    val startOpenSettings: String,
    val startBeginConversation: String,
    val startLoadingModel: String,
    val startChecking: String,
    val startModelNotInstalled: String,
    val startSetupModels: String,
    val startPreparing: String,
    // Settings
    val settingsTitle: String,
    val settingsBackToChat: String,
    val settingsSpeechInput: String,
    val settingsSttTitle: String,
    val settingsSttSubtitle: String,
    val settingsLanguageModel: String,
    val settingsManageModels: String,
    val settingsActivePrefix: String,
    val settingsOutputVoices: String,
    val settingsManageVoices: String,
    val settingsNetwork: String,
    val settingsExternalAccess: String,
    val settingsExternalAccessSubtitle: String,
    val settingsAdvanced: String,
    val settingsAdvancedTitle: String,
    val settingsAdvancedSubtitle: String,
    val settingsApp: String,
    val settingsInfo: String,
    val settingsInfoSubtitle: String,
    val settingsWizard: String,
    val settingsWizardSubtitle: String,
    val settingsLoadingModel: String,
    val settingsGoToChat: String,
    val settingsLanguage: String,
    val settingsLanguageSubtitle: String,
    // VoiceChat
    val vcTitle: String,
    val vcTitleDemo: String,
    val vcDistilling: String,
    val vcDistillingHint: String,
    val vcNewConversationTitle: String,
    val vcNewConversationText: String,
    val vcReset: String,
    val vcDistillBtn: String,
    val vcNewConvBtn: String,
    val vcHistoryBtn: String,
    val vcSettingsBtn: String,
    val vcContext: String,
    // Conversation
    val convReady: String,
    val convListening: String,
    val convThinking: String,
    val convSpeaking: String,
    val convStopOutput: String,
    val convMicOff: String,
    val convMicOn: String,
    val convYouPrefix: String,
    val convAssistantPrefix: String,
    val convEnterMessage: String,
    val convSend: String,
    // History
    val histTitle: String,
    val histDeleteHistory: String,
    val histResetTitle: String,
    val histResetText: String,
    val histResetBtn: String,
    val histNoConversation: String,
    val histCurrentSession: String,
    val histPreviousSessions: String,
    val histMsgSuffix: String,
    val histCollapse: String,
    val histExpand: String,
    // LLM Settings
    val llmTitle: String,
    val llmDescription: String,
    val llmRamTotal: String,
    val llmSystemBuffer: String,
    val llmContextWindow: String,
    val llmKvCache: String,
    val llmMaxByRam: String,
    val llmApplyRestart: String,
    val llmTokensSuffix: String,
    val llmLoaded: String,
    // Voice Settings
    val voiceTitle: String,
    val voiceDescription: String,
    val voiceExtracting: String,
    // System Prompt Settings
    val sysPromptTitle: String,
    val sysPromptHint: String,
    val sysPromptLabel: String,
    val sysPromptPreview: String,
    val sysPromptSaveRestart: String,
    val sysPromptClearBtn: String,
    // Advanced Settings
    val advTitle: String,
    val advSttMode: String,
    val advSttAndroid: String,
    val advSttAndroidDesc: String,
    val advSttLlmAudio: String,
    val advSttLlmAudioDesc: String,
    val advViewSection: String,
    val advExpertMode: String,
    val advExpertModeOn: String,
    val advExpertModeOff: String,
    val advAiMemory: String,
    val advWikiNotes: String,
    val advWikiOn: String,
    val advWikiOff: String,
    val advQaHistory: String,
    val advQaOn: String,
    val advQaOff: String,
    val advEntriesTotal: String,
    val advShowManage: String,
    val advDeleteAll: String,
    val advDeleteMemTitle: String,
    val advDeleteMemText: String,
    val advProcessing: String,
    val advUseGpu: String,
    val advGpuActive: String,
    val advCpuActive: String,
    val advPixelWarning: String,
    val advAssistant: String,
    val advEditSysPrompt: String,
    val advEditSysPromptSubtitle: String,
    val advExperimental: String,
    val advExperimentalSubtitle: String,
    // External Access
    val extTitle: String,
    val extWebSearch: String,
    val extDuckDuckGo: String,
    val extSearchOn: String,
    val extSearchOff: String,
    val extSearchDetail: String,
    // Memory Screen
    val memTitle: String,
    val memImportDone: String,
    val memDeleteTitle: String,
    val memDeleteText: String,
    val memImport: String,
    val memExport: String,
    val memExportTitle: String,
    val memTabPages: String,
    val memTabNotes: String,
    val memTabQa: String,
    // Wiki Pages Tab
    val wikiNoPages: String,
    val wikiHint: String,
    val wikiNewPage: String,
    val wikiTitleLabel: String,
    val wikiContentLabel: String,
    val wikiCreate: String,
    val wikiEditPage: String,
    val wikiDescription: String,
    val wikiEdit: String,
    // Wiki Notes Tab
    val notesEmpty: String,
    val notesHint: String,
    val notesDescription: String,
    // Q&A Tab
    val qaEmpty: String,
    val qaDescription: String,
    val qaYou: String,
    val qaAi: String,
    // Info Screen
    val infoTitle: String,
    val infoSubtitle: String,
    val infoUsed: String,
    // Language Screen
    val langTitle: String,
    val langSubtitle: String,
    val langDeTitle: String,
    val langEnTitle: String,
    val langMultiTitle: String,
    val langDeDesc: String,
    val langEnDesc: String,
    val langMultiDesc: String,
    val langRestartNote: String,
)

val AppStringsDe = AppStrings(
    back = "Zurück",
    cancel = "Abbrechen",
    delete = "Löschen",
    save = "Speichern",
    activate = "Aktivieren",
    download = "Herunterladen",
    retry = "Erneut versuchen",
    errorLabel = "Fehler",
    activeLabel = "Aktiv",
    ok = "OK",
    wizardWelcome = "Willkommen bei Kern",
    wizardSubtitle = "Kern ist ein lokaler Sprachassistent der komplett offline auf deinem Gerät läuft.",
    wizardEasySetupInfo = "Easy Setup lädt automatisch:",
    wizardEasySetupLlm = "• Gemma 4 E2B – Sprachmodell (~2,6 GB)",
    wizardEasySetupVoice = "• Thorsten (mittel) – Stimme (~75 MB)",
    wizardEasySetupTotal = "Gesamt ca. 2,7 GB · WLAN empfohlen",
    wizardStartEasySetup = "Easy Setup starten",
    wizardSkip = "Ohne Setup fortfahren",
    wizardModelLabel = "Modell",
    wizardVoiceLabel = "Stimme",
    wizardStarting = "Wird gestartet …",
    wizardExtracting = "wird entpackt …",
    wizardReady = "bereit ✓",
    wizardLangTitle = "Sprache wählen",
    wizardLangSubtitle = "In welcher Sprache soll der Assistent mit dir sprechen?",
    wizardMemoryTitle = "Dauerhaftes Gedächtnis?",
    wizardMemorySubtitle = "Soll Kern sich nach jedem Gespräch Dinge über dich merken?",
    wizardMemoryYes = "Ja, Gedächtnis aktivieren",
    wizardMemoryYesDesc = "Gespräche werden nach jeder Unterhaltung automatisch verarbeitet",
    wizardMemoryNo = "Nein, ohne Gedächtnis starten",
    wizardMemoryNoDesc = "Jedes Gespräch beginnt ohne Vorwissen — weniger Ressourcen",
    wizardMemoryHint = "Macht Antworten etwas langsamer · kann jederzeit in den Erweiterten Einstellungen geändert werden",
    startSubtitle = "Lokaler Sprachassistent",
    startOpenSettings = "Einstellungen öffnen",
    startBeginConversation = "Unterhaltung beginnen",
    startLoadingModel = "Sprachmodell wird geladen …",
    startChecking = "Wird überprüft …",
    startModelNotInstalled = "Sprachmodell noch nicht installiert.",
    startSetupModels = "Modelle einrichten",
    startPreparing = "Wird vorbereitet …",
    settingsTitle = "Einstellungen",
    settingsBackToChat = "Zurück zum Chat",
    settingsSpeechInput = "Spracheingabe",
    settingsSttTitle = "Sprache → Text (STT)",
    settingsSttSubtitle = "Android SpeechRecognizer – kein Download nötig",
    settingsLanguageModel = "Sprachmodell",
    settingsManageModels = "Modell verwalten",
    settingsActivePrefix = "Aktiv: ",
    settingsOutputVoices = "Ausgabe-Stimmen",
    settingsManageVoices = "Stimmen verwalten",
    settingsNetwork = "Netzwerk",
    settingsExternalAccess = "Externe Zugriffe",
    settingsExternalAccessSubtitle = "Websuche und Internetverbindung",
    settingsAdvanced = "Erweitert",
    settingsAdvancedTitle = "Erweiterte Einstellungen",
    settingsAdvancedSubtitle = "Verarbeitung, Systemprompt, Experten-Modus",
    settingsApp = "App",
    settingsInfo = "Info",
    settingsInfoSubtitle = "Version & Lizenzinformationen",
    settingsWizard = "Setup-Wizard",
    settingsWizardSubtitle = "Sprache und Modelle neu einrichten",
    settingsLoadingModel = "Sprachmodell wird geladen …",
    settingsGoToChat = "Zum Sprach-Chat",
    settingsLanguage = "Sprache & Region",
    settingsLanguageSubtitle = "Assistent-Sprache und Spracherkennung",
    vcTitle = "Sprach-Assistent",
    vcTitleDemo = "Sprach-Assistent – Demo",
    vcDistilling = "Erinnerungen werden gespeichert …",
    vcDistillingHint = "Das LLM destilliert die Unterhaltung.",
    vcNewConversationTitle = "Neue Unterhaltung?",
    vcNewConversationText = "Der aktuelle Verlauf und das Gesprächsgedächtnis des LLM werden gelöscht. Das nächste Gespräch beginnt von vorn.",
    vcReset = "Zurücksetzen",
    vcDistillBtn = "Gespräch destillieren",
    vcNewConvBtn = "Neue Unterhaltung",
    vcHistoryBtn = "Gesprächsverlauf",
    vcSettingsBtn = "Einstellungen",
    vcContext = "Kontext",
    convReady = "Bereit",
    convListening = "Ich höre zu …",
    convThinking = "Denke nach …",
    convSpeaking = "Spreche …",
    convStopOutput = "Ausgabe stoppen",
    convMicOff = "Mikrofon ausschalten",
    convMicOn = "Mikrofon einschalten",
    convYouPrefix = "Du: ",
    convAssistantPrefix = "Assistent: ",
    convEnterMessage = "Nachricht eingeben",
    convSend = "Senden",
    histTitle = "Gesprächsverlauf",
    histDeleteHistory = "Verlauf löschen",
    histResetTitle = "Gespräch zurücksetzen?",
    histResetText = "Der aktuelle Verlauf und das Gesprächsgedächtnis des LLM werden gelöscht. Das nächste Gespräch beginnt von vorn.",
    histResetBtn = "Zurücksetzen",
    histNoConversation = "Noch kein Gespräch in dieser Sitzung.",
    histCurrentSession = "Aktuelle Sitzung",
    histPreviousSessions = "Frühere Sitzungen",
    histMsgSuffix = " Msg",
    histCollapse = "Einklappen",
    histExpand = "Ausklappen",
    llmTitle = "Sprachmodell",
    llmDescription = "Lade ein Modell herunter, wechsle das aktive Modell oder lösche nicht mehr benötigte.",
    llmRamTotal = "Gerät-RAM gesamt",
    llmSystemBuffer = "Systempuffer",
    llmContextWindow = "Kontextfenster",
    llmKvCache = "KV-Cache",
    llmMaxByRam = "max. mit RAM",
    llmApplyRestart = "Übernehmen & neu starten",
    llmTokensSuffix = " Tokens",
    llmLoaded = "geladen …",
    voiceTitle = "Ausgabe-Stimmen",
    voiceDescription = "Lade Stimmen herunter, wechsle die aktive Stimme oder lösche nicht mehr benötigte.",
    voiceExtracting = "Entpacken …",
    sysPromptTitle = "Systemprompt",
    sysPromptHint = "Leer lassen für den Standard-Systemprompt. Der Such-Zusatz wird automatisch angehängt wenn die Websuche aktiv ist.",
    sysPromptLabel = "Systemprompt",
    sysPromptPreview = "Vorschau aktiver Prompt:",
    sysPromptSaveRestart = "Speichern & neu starten",
    sysPromptClearBtn = "Zurücksetzen",
    advTitle = "Erweiterte Einstellungen",
    advSttMode = "Spracheingabe-Modus",
    advSttAndroid = "Android STT (Standard)",
    advSttAndroidDesc = "Schnell · offline via Android SpeechRecognizer",
    advSttLlmAudio = "LLM Audio (experimentell)",
    advSttLlmAudioDesc = "Gemma 4 versteht Audio direkt — ohne Text-Zwischenschritt",
    advViewSection = "Ansicht",
    advExpertMode = "Experten-Modus",
    advExpertModeOn = "Kontextfenster, RAM-Anzeige und weitere Optionen sichtbar",
    advExpertModeOff = "Erweiterte Optionen ausgeblendet",
    advAiMemory = "KI-Gedächtnis",
    advWikiNotes = "Wiki-Notizen (LLM)",
    advWikiOn = "Aktiv · Wiki-Kontext im Systemprompt + Gedächtnis-Suche",
    advWikiOff = "Inaktiv · kein Wiki-Kontext, search_memories deaktiviert",
    advQaHistory = "Q&A-Verlauf (automatisch)",
    advQaOn = "Aktiv · Gesprächspaare als BM25-Retrieval-Basis",
    advQaOff = "Inaktiv · kein automatisches Speichern",
    advEntriesTotal = " Einträge gesamt · ",
    advShowManage = "Einträge anzeigen & verwalten",
    advDeleteAll = "Alles löschen",
    advDeleteMemTitle = "Gedächtnis löschen?",
    advDeleteMemText = "gespeicherten Gesprächseinträge werden dauerhaft gelöscht. Der Assistent verliert sein erlerntes Kontextwissen.",
    advProcessing = "Verarbeitung",
    advUseGpu = "GPU nutzen",
    advGpuActive = "Aktiv: GPU",
    advCpuActive = "Aktiv: CPU",
    advPixelWarning = "⚠ Pixel-Geräte mit Tensor-Chip unterstützen GPU nicht (kein OpenCL-Zugriff). Bitte CPU verwenden.",
    advAssistant = "Assistent",
    advEditSysPrompt = "Systemprompt bearbeiten",
    advEditSysPromptSubtitle = "Verhalten und Persönlichkeit des Assistenten anpassen",
    advExperimental = "Experimentell",
    advExperimentalSubtitle = "Funktionen in Entwicklung · nur im Experten-Modus sichtbar",
    extTitle = "Externe Zugriffe",
    extWebSearch = "Websuche",
    extDuckDuckGo = "DuckDuckGo-Suche",
    extSearchOn = "Aktiv · Gemma kann das Internet durchsuchen",
    extSearchOff = "Inaktiv · Kein Internetzugriff",
    extSearchDetail = "Suche über DuckDuckGo Instant Answers API · kein Login oder API-Key nötig · Ergebnisse werden dem LLM als Tool-Antwort übergeben · Gemma entscheidet selbst, wann eine Suche sinnvoll ist",
    memTitle = "KI-Gedächtnis",
    memImportDone = "Import abgeschlossen",
    memDeleteTitle = "Gedächtnis löschen?",
    memDeleteText = "Alle gespeicherten Wiki-Seiten, Notizen und Q&A-Einträge werden dauerhaft gelöscht.",
    memImport = "Importieren",
    memExport = "Exportieren",
    memExportTitle = "Wiki exportieren",
    memTabPages = "Seiten",
    memTabNotes = "Notizen",
    memTabQa = "Q&A",
    wikiNoPages = "Noch keine Wiki-Seiten.",
    wikiHint = "Das LLM destilliert Gespräche (ab 3 Nachrichten)\nautomatisch in Wissensseiten.",
    wikiNewPage = "Neue Seite",
    wikiTitleLabel = "Titel",
    wikiContentLabel = "Inhalt",
    wikiCreate = "Erstellen",
    wikiEditPage = "Seite bearbeiten",
    wikiDescription = "Vom LLM gepflegte Wissensseiten — zuletzt aktualisiert zuerst",
    wikiEdit = "Bearbeiten",
    notesEmpty = "Noch keine Wiki-Notizen.",
    notesHint = "Das LLM schreibt hier eigene Notizen wenn es\netwas Wichtiges über dich erfährt.",
    notesDescription = "Vom LLM selbst verfasste Notizen — neueste zuerst",
    qaEmpty = "Noch keine Q&A-Einträge.",
    qaDescription = "Automatisch gespeicherte Gesprächspaare — neueste zuerst",
    qaYou = "Du",
    qaAi = "KI",
    infoTitle = "Info",
    infoSubtitle = "Lokaler Sprachassistent",
    infoUsed = "Verwendet",
    langTitle = "Sprache & Region",
    langSubtitle = "Assistent-Sprache und Spracherkennung (STT)",
    langDeTitle = "Deutsch",
    langEnTitle = "English",
    langMultiTitle = "Multilingual",
    langDeDesc = "Assistent antwortet auf Deutsch · STT: de-DE",
    langEnDesc = "Assistent antwortet auf Englisch · STT: en-US",
    langMultiDesc = "Assistent antwortet in der Sprache des Nutzers · STT: de-DE",
    langRestartNote = "Wird beim nächsten Neustart der Engine übernommen.",
)

val AppStringsEn = AppStrings(
    back = "Back",
    cancel = "Cancel",
    delete = "Delete",
    save = "Save",
    activate = "Activate",
    download = "Download",
    retry = "Try again",
    errorLabel = "Error",
    activeLabel = "Active",
    ok = "OK",
    wizardWelcome = "Welcome to Kern",
    wizardSubtitle = "Kern is a local voice assistant that runs completely offline on your device.",
    wizardEasySetupInfo = "Easy Setup downloads automatically:",
    wizardEasySetupLlm = "• Gemma 4 E2B – Language model (~2.6 GB)",
    wizardEasySetupVoice = "• Amy (US) – Voice (~25 MB)",
    wizardEasySetupTotal = "Total ~2.6 GB · Wi-Fi recommended",
    wizardStartEasySetup = "Start Easy Setup",
    wizardSkip = "Continue without Setup",
    wizardModelLabel = "Model",
    wizardVoiceLabel = "Voice",
    wizardStarting = "Starting …",
    wizardExtracting = "extracting …",
    wizardReady = "ready ✓",
    wizardLangTitle = "Choose Language",
    wizardLangSubtitle = "Which language should the assistant speak with you?",
    wizardMemoryTitle = "Persistent Memory?",
    wizardMemorySubtitle = "Should Kern remember things about you after each conversation?",
    wizardMemoryYes = "Yes, enable memory",
    wizardMemoryYesDesc = "Conversations are automatically processed after each session",
    wizardMemoryNo = "No, start without memory",
    wizardMemoryNoDesc = "Each conversation starts fresh — fewer resources used",
    wizardMemoryHint = "Makes responses slightly slower · can be changed anytime in Advanced Settings",
    startSubtitle = "Local Voice Assistant",
    startOpenSettings = "Open Settings",
    startBeginConversation = "Start Conversation",
    startLoadingModel = "Loading language model …",
    startChecking = "Checking …",
    startModelNotInstalled = "Language model not installed.",
    startSetupModels = "Set up Models",
    startPreparing = "Preparing …",
    settingsTitle = "Settings",
    settingsBackToChat = "Back to Chat",
    settingsSpeechInput = "Speech Input",
    settingsSttTitle = "Speech → Text (STT)",
    settingsSttSubtitle = "Android SpeechRecognizer – no download needed",
    settingsLanguageModel = "Language Model",
    settingsManageModels = "Manage Models",
    settingsActivePrefix = "Active: ",
    settingsOutputVoices = "Output Voices",
    settingsManageVoices = "Manage Voices",
    settingsNetwork = "Network",
    settingsExternalAccess = "External Access",
    settingsExternalAccessSubtitle = "Web search and internet connection",
    settingsAdvanced = "Advanced",
    settingsAdvancedTitle = "Advanced Settings",
    settingsAdvancedSubtitle = "Processing, System Prompt, Expert Mode",
    settingsApp = "App",
    settingsInfo = "Info",
    settingsInfoSubtitle = "Version & License information",
    settingsWizard = "Setup Wizard",
    settingsWizardSubtitle = "Configure language and models again",
    settingsLoadingModel = "Loading language model …",
    settingsGoToChat = "Go to Voice Chat",
    settingsLanguage = "Language & Region",
    settingsLanguageSubtitle = "Assistant language and speech recognition",
    vcTitle = "Voice Assistant",
    vcTitleDemo = "Voice Assistant – Demo",
    vcDistilling = "Saving memories …",
    vcDistillingHint = "The LLM is distilling the conversation.",
    vcNewConversationTitle = "New Conversation?",
    vcNewConversationText = "The current history and LLM memory will be deleted. The next conversation starts fresh.",
    vcReset = "Reset",
    vcDistillBtn = "Distill Conversation",
    vcNewConvBtn = "New Conversation",
    vcHistoryBtn = "Conversation History",
    vcSettingsBtn = "Settings",
    vcContext = "Context",
    convReady = "Ready",
    convListening = "Listening …",
    convThinking = "Thinking …",
    convSpeaking = "Speaking …",
    convStopOutput = "Stop output",
    convMicOff = "Turn off microphone",
    convMicOn = "Turn on microphone",
    convYouPrefix = "You: ",
    convAssistantPrefix = "Assistant: ",
    convEnterMessage = "Enter message",
    convSend = "Send",
    histTitle = "Conversation History",
    histDeleteHistory = "Delete history",
    histResetTitle = "Reset Conversation?",
    histResetText = "The current history and LLM memory will be deleted. The next conversation starts fresh.",
    histResetBtn = "Reset",
    histNoConversation = "No conversation in this session yet.",
    histCurrentSession = "Current Session",
    histPreviousSessions = "Previous Sessions",
    histMsgSuffix = " Msg",
    histCollapse = "Collapse",
    histExpand = "Expand",
    llmTitle = "Language Model",
    llmDescription = "Download a model, switch the active model, or delete unused ones.",
    llmRamTotal = "Total device RAM",
    llmSystemBuffer = "System buffer",
    llmContextWindow = "Context window",
    llmKvCache = "KV-Cache",
    llmMaxByRam = "max. with RAM",
    llmApplyRestart = "Apply & restart",
    llmTokensSuffix = " tokens",
    llmLoaded = "loaded …",
    voiceTitle = "Output Voices",
    voiceDescription = "Download voices, switch the active voice, or delete unused ones.",
    voiceExtracting = "Extracting …",
    sysPromptTitle = "System Prompt",
    sysPromptHint = "Leave blank for the default system prompt. The search addon is automatically appended when web search is active.",
    sysPromptLabel = "System Prompt",
    sysPromptPreview = "Preview active prompt:",
    sysPromptSaveRestart = "Save & restart",
    sysPromptClearBtn = "Reset",
    advTitle = "Advanced Settings",
    advSttMode = "Speech Input Mode",
    advSttAndroid = "Android STT (default)",
    advSttAndroidDesc = "Fast · offline via Android SpeechRecognizer",
    advSttLlmAudio = "LLM Audio (experimental)",
    advSttLlmAudioDesc = "Gemma 4 understands audio directly — no text transcription step",
    advViewSection = "View",
    advExpertMode = "Expert Mode",
    advExpertModeOn = "Context window, RAM display and more options visible",
    advExpertModeOff = "Advanced options hidden",
    advAiMemory = "AI Memory",
    advWikiNotes = "Wiki Notes (LLM)",
    advWikiOn = "Active · Wiki context in system prompt + memory search",
    advWikiOff = "Inactive · no wiki context, search_memories disabled",
    advQaHistory = "Q&A History (automatic)",
    advQaOn = "Active · Conversation pairs as BM25 retrieval basis",
    advQaOff = "Inactive · no automatic saving",
    advEntriesTotal = " entries total · ",
    advShowManage = "View & manage entries",
    advDeleteAll = "Delete all",
    advDeleteMemTitle = "Delete Memory?",
    advDeleteMemText = "saved conversation entries will be permanently deleted. The assistant will lose its learned context.",
    advProcessing = "Processing",
    advUseGpu = "Use GPU",
    advGpuActive = "Active: GPU",
    advCpuActive = "Active: CPU",
    advPixelWarning = "⚠ Pixel devices with Tensor chip do not support GPU (no OpenCL access). Please use CPU.",
    advAssistant = "Assistant",
    advEditSysPrompt = "Edit System Prompt",
    advEditSysPromptSubtitle = "Customize assistant behavior and personality",
    advExperimental = "Experimental",
    advExperimentalSubtitle = "Features in development · only visible in Expert Mode",
    extTitle = "External Access",
    extWebSearch = "Web Search",
    extDuckDuckGo = "DuckDuckGo Search",
    extSearchOn = "Active · Gemma can search the internet",
    extSearchOff = "Inactive · No internet access",
    extSearchDetail = "Search via DuckDuckGo Instant Answers API · no login or API key required · results passed to LLM as tool response · Gemma decides when to search",
    memTitle = "AI Memory",
    memImportDone = "Import complete",
    memDeleteTitle = "Delete Memory?",
    memDeleteText = "All saved wiki pages, notes and Q&A entries will be permanently deleted.",
    memImport = "Import",
    memExport = "Export",
    memExportTitle = "Export Wiki",
    memTabPages = "Pages",
    memTabNotes = "Notes",
    memTabQa = "Q&A",
    wikiNoPages = "No wiki pages yet.",
    wikiHint = "The LLM automatically distills conversations (from 3 messages)\ninto knowledge pages.",
    wikiNewPage = "New Page",
    wikiTitleLabel = "Title",
    wikiContentLabel = "Content",
    wikiCreate = "Create",
    wikiEditPage = "Edit Page",
    wikiDescription = "Knowledge pages maintained by the LLM — most recently updated first",
    wikiEdit = "Edit",
    notesEmpty = "No wiki notes yet.",
    notesHint = "The LLM writes its own notes here when it\nlearns something important about you.",
    notesDescription = "Notes written by the LLM itself — newest first",
    qaEmpty = "No Q&A entries yet.",
    qaDescription = "Automatically saved conversation pairs — newest first",
    qaYou = "You",
    qaAi = "AI",
    infoTitle = "Info",
    infoSubtitle = "Local Voice Assistant",
    infoUsed = "Used",
    langTitle = "Language & Region",
    langSubtitle = "Assistant language and speech recognition (STT)",
    langDeTitle = "Deutsch",
    langEnTitle = "English",
    langMultiTitle = "Multilingual",
    langDeDesc = "Assistant responds in German · STT: de-DE",
    langEnDesc = "Assistant responds in English · STT: en-US",
    langMultiDesc = "Assistant responds in the user's language · STT: de-DE",
    langRestartNote = "Takes effect on next engine restart.",
)

// Multilingual uses German UI strings
val AppStringsMulti = AppStringsDe.copy(
    langDeDesc = "Assistent antwortet auf Deutsch · STT: de-DE",
    langEnDesc = "Assistent antwortet auf Englisch · STT: en-US",
    langMultiDesc = "Assistent antwortet in der Sprache des Nutzers · STT: de-DE",
)

val LocalStrings = compositionLocalOf { AppStringsDe }
